// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_bricklink_items from "./routes/api/bricklink-items.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_parse_shopee from "./routes/api/parse-shopee.ts";
import * as $api_scrape_bricklink from "./routes/api/scrape-bricklink.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ShopeeParser from "./islands/ShopeeParser.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/bricklink-items.ts": $api_bricklink_items,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/parse-shopee.ts": $api_parse_shopee,
    "./routes/api/scrape-bricklink.ts": $api_scrape_bricklink,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/ShopeeParser.tsx": $ShopeeParser,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
