// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $analysis_demo from "./routes/analysis-demo.tsx";
import * as $api_analysis_productId_ from "./routes/api/analysis/[productId].ts";
import * as $api_analysis_batch from "./routes/api/analysis/batch.ts";
import * as $api_analysis_strategies from "./routes/api/analysis/strategies.ts";
import * as $api_bricklink_items from "./routes/api/bricklink-items.ts";
import * as $api_detect_missing_data from "./routes/api/detect-missing-data.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_parse_brickeconomy from "./routes/api/parse-brickeconomy.ts";
import * as $api_parse_shopee from "./routes/api/parse-shopee.ts";
import * as $api_parse_toysrus from "./routes/api/parse-toysrus.ts";
import * as $api_products from "./routes/api/products.ts";
import * as $api_products_id_ from "./routes/api/products/[id].ts";
import * as $api_products_id_tags from "./routes/api/products/[id]/tags.ts";
import * as $api_products_bulk_tag from "./routes/api/products/bulk-tag.ts";
import * as $api_products_manual from "./routes/api/products/manual.ts";
import * as $api_products_validate_and_save from "./routes/api/products/validate-and-save.ts";
import * as $api_queue_reset from "./routes/api/queue-reset.ts";
import * as $api_raw_data_id_ from "./routes/api/raw-data/[id].ts";
import * as $api_raw_data_session_sessionId_ from "./routes/api/raw-data/session/[sessionId].ts";
import * as $api_raw_data_stats from "./routes/api/raw-data/stats.ts";
import * as $api_reddit_results from "./routes/api/reddit-results.ts";
import * as $api_reddit_search from "./routes/api/reddit-search.ts";
import * as $api_scrape_bricklink from "./routes/api/scrape-bricklink.ts";
import * as $api_scrape_queue_status from "./routes/api/scrape-queue-status.ts";
import * as $api_scrape_scheduler from "./routes/api/scrape-scheduler.ts";
import * as $api_shopee_items from "./routes/api/shopee-items.ts";
import * as $api_tags from "./routes/api/tags.ts";
import * as $api_tags_cleanup_expired from "./routes/api/tags/cleanup-expired.ts";
import * as $api_value_investing_productId_ from "./routes/api/value-investing/[productId].ts";
import * as $api_vouchers from "./routes/api/vouchers.ts";
import * as $bricklink_items from "./routes/bricklink-items.tsx";
import * as $buy from "./routes/buy.tsx";
import * as $cart from "./routes/cart.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $products from "./routes/products.tsx";
import * as $products_id_ from "./routes/products/[id].tsx";
import * as $queue from "./routes/queue.tsx";
import * as $tags from "./routes/tags.tsx";
import * as $vouchers from "./routes/vouchers.tsx";
import * as $BricklinkProductsList from "./islands/BricklinkProductsList.tsx";
import * as $CartManager from "./islands/CartManager.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $IntrinsicValueCard from "./islands/IntrinsicValueCard.tsx";
import * as $PricingOverview from "./islands/PricingOverview.tsx";
import * as $ProductEditModal from "./islands/ProductEditModal.tsx";
import * as $ProductImageGallery from "./islands/ProductImageGallery.tsx";
import * as $ProductsList from "./islands/ProductsList.tsx";
import * as $QueueDiagnosticsDashboard from "./islands/QueueDiagnosticsDashboard.tsx";
import * as $ShopeeParser from "./islands/ShopeeParser.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $TagManager from "./islands/TagManager.tsx";
import * as $UnifiedParser from "./islands/UnifiedParser.tsx";
import * as $ValueInvestingDashboard from "./islands/ValueInvestingDashboard.tsx";
import * as $VoucherEditModal from "./islands/VoucherEditModal.tsx";
import * as $VoucherSelector from "./islands/VoucherSelector.tsx";
import * as $VouchersList from "./islands/VouchersList.tsx";
import * as $components_ErrorBoundary from "./islands/components/ErrorBoundary.tsx";
import * as $components_IntrinsicValueProgressBar from "./islands/components/IntrinsicValueProgressBar.tsx";
import * as $components_QueueHealthBanner from "./islands/components/QueueHealthBanner.tsx";
import * as $components_QueueStatsBanner from "./islands/components/QueueStatsBanner.tsx";
import * as $components_SyncStatusBadge from "./islands/components/SyncStatusBadge.tsx";
import * as $components_ValueRatingBadge from "./islands/components/ValueRatingBadge.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/analysis-demo.tsx": $analysis_demo,
    "./routes/api/analysis/[productId].ts": $api_analysis_productId_,
    "./routes/api/analysis/batch.ts": $api_analysis_batch,
    "./routes/api/analysis/strategies.ts": $api_analysis_strategies,
    "./routes/api/bricklink-items.ts": $api_bricklink_items,
    "./routes/api/detect-missing-data.ts": $api_detect_missing_data,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/parse-brickeconomy.ts": $api_parse_brickeconomy,
    "./routes/api/parse-shopee.ts": $api_parse_shopee,
    "./routes/api/parse-toysrus.ts": $api_parse_toysrus,
    "./routes/api/products.ts": $api_products,
    "./routes/api/products/[id].ts": $api_products_id_,
    "./routes/api/products/[id]/tags.ts": $api_products_id_tags,
    "./routes/api/products/bulk-tag.ts": $api_products_bulk_tag,
    "./routes/api/products/manual.ts": $api_products_manual,
    "./routes/api/products/validate-and-save.ts":
      $api_products_validate_and_save,
    "./routes/api/queue-reset.ts": $api_queue_reset,
    "./routes/api/raw-data/[id].ts": $api_raw_data_id_,
    "./routes/api/raw-data/session/[sessionId].ts":
      $api_raw_data_session_sessionId_,
    "./routes/api/raw-data/stats.ts": $api_raw_data_stats,
    "./routes/api/reddit-results.ts": $api_reddit_results,
    "./routes/api/reddit-search.ts": $api_reddit_search,
    "./routes/api/scrape-bricklink.ts": $api_scrape_bricklink,
    "./routes/api/scrape-queue-status.ts": $api_scrape_queue_status,
    "./routes/api/scrape-scheduler.ts": $api_scrape_scheduler,
    "./routes/api/shopee-items.ts": $api_shopee_items,
    "./routes/api/tags.ts": $api_tags,
    "./routes/api/tags/cleanup-expired.ts": $api_tags_cleanup_expired,
    "./routes/api/value-investing/[productId].ts":
      $api_value_investing_productId_,
    "./routes/api/vouchers.ts": $api_vouchers,
    "./routes/bricklink-items.tsx": $bricklink_items,
    "./routes/buy.tsx": $buy,
    "./routes/cart.tsx": $cart,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/products.tsx": $products,
    "./routes/products/[id].tsx": $products_id_,
    "./routes/queue.tsx": $queue,
    "./routes/tags.tsx": $tags,
    "./routes/vouchers.tsx": $vouchers,
  },
  islands: {
    "./islands/BricklinkProductsList.tsx": $BricklinkProductsList,
    "./islands/CartManager.tsx": $CartManager,
    "./islands/Counter.tsx": $Counter,
    "./islands/IntrinsicValueCard.tsx": $IntrinsicValueCard,
    "./islands/PricingOverview.tsx": $PricingOverview,
    "./islands/ProductEditModal.tsx": $ProductEditModal,
    "./islands/ProductImageGallery.tsx": $ProductImageGallery,
    "./islands/ProductsList.tsx": $ProductsList,
    "./islands/QueueDiagnosticsDashboard.tsx": $QueueDiagnosticsDashboard,
    "./islands/ShopeeParser.tsx": $ShopeeParser,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/TagManager.tsx": $TagManager,
    "./islands/UnifiedParser.tsx": $UnifiedParser,
    "./islands/ValueInvestingDashboard.tsx": $ValueInvestingDashboard,
    "./islands/VoucherEditModal.tsx": $VoucherEditModal,
    "./islands/VoucherSelector.tsx": $VoucherSelector,
    "./islands/VouchersList.tsx": $VouchersList,
    "./islands/components/ErrorBoundary.tsx": $components_ErrorBoundary,
    "./islands/components/IntrinsicValueProgressBar.tsx":
      $components_IntrinsicValueProgressBar,
    "./islands/components/QueueHealthBanner.tsx": $components_QueueHealthBanner,
    "./islands/components/QueueStatsBanner.tsx": $components_QueueStatsBanner,
    "./islands/components/SyncStatusBadge.tsx": $components_SyncStatusBadge,
    "./islands/components/ValueRatingBadge.tsx": $components_ValueRatingBadge,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
