"""initial schema - all 28 tables

Revision ID: 10f2bdce6adf
Revises: 
Create Date: 2026-04-04 09:43:33.466274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10f2bdce6adf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brickeconomy_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('subtheme', sa.String(length=100), nullable=True),
    sa.Column('year_released', sa.Integer(), nullable=True),
    sa.Column('year_retired', sa.Integer(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('minifigs', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('retiring_soon', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('brickeconomy_url', sa.Text(), nullable=True),
    sa.Column('rrp_usd_cents', sa.Integer(), nullable=True),
    sa.Column('rrp_gbp_cents', sa.Integer(), nullable=True),
    sa.Column('rrp_eur_cents', sa.Integer(), nullable=True),
    sa.Column('value_new_cents', sa.Integer(), nullable=True),
    sa.Column('value_used_cents', sa.Integer(), nullable=True),
    sa.Column('annual_growth_pct', sa.Float(), nullable=True),
    sa.Column('rating_value', sa.String(length=20), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('future_estimate_cents', sa.Integer(), nullable=True),
    sa.Column('future_estimate_date', sa.String(length=50), nullable=True),
    sa.Column('distribution_mean_cents', sa.Integer(), nullable=True),
    sa.Column('distribution_stddev_cents', sa.Integer(), nullable=True),
    sa.Column('value_chart_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sales_trend_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candlestick_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('release_date', sa.String(length=50), nullable=True),
    sa.Column('retired_date', sa.String(length=50), nullable=True),
    sa.Column('minifig_value_cents', sa.Integer(), nullable=True),
    sa.Column('exclusive_minifigs', sa.Boolean(), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('designer', sa.String(length=200), nullable=True),
    sa.Column('rrp_cad_cents', sa.Integer(), nullable=True),
    sa.Column('rrp_aud_cents', sa.Integer(), nullable=True),
    sa.Column('used_value_low_cents', sa.Integer(), nullable=True),
    sa.Column('used_value_high_cents', sa.Integer(), nullable=True),
    sa.Column('total_growth_pct', sa.Float(), nullable=True),
    sa.Column('rolling_growth_pct', sa.Float(), nullable=True),
    sa.Column('growth_90d_pct', sa.Float(), nullable=True),
    sa.Column('theme_rank', sa.Integer(), nullable=True),
    sa.Column('subtheme_avg_growth_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Append-only BrickEconomy snapshots per scrape'
    )
    op.create_table('bricklink_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('year_released', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('parts_count', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('minifig_count', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(length=200), nullable=True),
    sa.Column('has_instructions', sa.Boolean(), nullable=True),
    sa.Column('watch_status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('scrape_interval_days', sa.Integer(), server_default='7', nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_scrape_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('bricklink_monthly_sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('times_sold', sa.Integer(), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('min_price', sa.Integer(), nullable=True),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('avg_price', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='BrickLink monthly sales aggregates'
    )
    op.create_table('bricklink_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('six_month_new', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('six_month_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_new', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bricklink_price_history_item_id'), 'bricklink_price_history', ['item_id'], unique=False)
    op.create_table('google_trends_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('search_property', sa.String(length=50), server_default='youtube', nullable=False),
    sa.Column('geo', sa.String(length=10), server_default='', nullable=False),
    sa.Column('timeframe_start', sa.String(length=20), nullable=True),
    sa.Column('timeframe_end', sa.String(length=20), nullable=True),
    sa.Column('interest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('peak_value', sa.Integer(), nullable=True),
    sa.Column('peak_date', sa.String(length=20), nullable=True),
    sa.Column('average_value', sa.Float(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('google_trends_theme_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('theme_type', sa.String(length=50), server_default='generic', nullable=False),
    sa.Column('keyword_lego', sa.String(length=200), nullable=False),
    sa.Column('keyword_bare', sa.String(length=200), server_default='', nullable=False),
    sa.Column('search_property', sa.String(length=50), server_default='youtube', nullable=False),
    sa.Column('geo', sa.String(length=10), server_default='', nullable=False),
    sa.Column('timeframe_start', sa.String(length=20), nullable=True),
    sa.Column('timeframe_end', sa.String(length=20), nullable=True),
    sa.Column('interest_lego_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interest_bare_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_lego', sa.Float(), nullable=True),
    sa.Column('avg_bare', sa.Float(), nullable=True),
    sa.Column('peak_lego', sa.Integer(), nullable=True),
    sa.Column('peak_bare', sa.Integer(), nullable=True),
    sa.Column('lego_share', sa.Float(), nullable=True),
    sa.Column('n_weeks', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), server_default='image/png', nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'item_id', name='uq_image_assets')
    )
    op.create_table('keepa_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('keepa_url', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_buy_box_cents', sa.Integer(), nullable=True),
    sa.Column('current_amazon_cents', sa.Integer(), nullable=True),
    sa.Column('current_new_cents', sa.Integer(), nullable=True),
    sa.Column('lowest_ever_cents', sa.Integer(), nullable=True),
    sa.Column('highest_ever_cents', sa.Integer(), nullable=True),
    sa.Column('amazon_price_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_price_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_3p_fba_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_3p_fbm_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('used_price_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('used_like_new_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('buy_box_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('list_price_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warehouse_deals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collectible_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sales_rank_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('tracking_users', sa.Integer(), nullable=True),
    sa.Column('chart_screenshot_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lego_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('year_released', sa.Integer(), nullable=True),
    sa.Column('year_retired', sa.Integer(), nullable=True),
    sa.Column('parts_count', sa.Integer(), nullable=True),
    sa.Column('weight', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('rrp_cents', sa.Integer(), nullable=True),
    sa.Column('rrp_currency', sa.String(length=10), server_default='MYR', nullable=True),
    sa.Column('retiring_soon', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('watchlist', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_rating', sa.Integer(), nullable=True),
    sa.Column('minifig_count', sa.Integer(), nullable=True),
    sa.Column('dimensions', sa.String(length=200), nullable=True),
    sa.Column('release_date', sa.String(length=50), nullable=True),
    sa.Column('retired_date', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_number')
    )
    op.create_table('mightyutan_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('price_myr', sa.String(length=20), nullable=False),
    sa.Column('available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mightyutan_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price_myr', sa.String(length=20), nullable=True),
    sa.Column('original_price_myr', sa.String(length=20), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_sold', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('minifig_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minifig_id', sa.String(length=50), nullable=False),
    sa.Column('six_month_new', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('six_month_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_new', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_minifig_price_history_minifig_id'), 'minifig_price_history', ['minifig_id'], unique=False)
    op.create_table('minifigures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('minifig_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('year_released', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('minifig_id')
    )
    op.create_table('ml_feature_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_return', sa.Float(), nullable=True),
    sa.Column('target_profitable', sa.Boolean(), nullable=True),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_number', 'horizon_months', name='uq_ml_feature_store')
    )
    op.create_table('ml_model_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=50), nullable=False),
    sa.Column('r_squared', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('quintile_spread', sa.Float(), nullable=True),
    sa.Column('n_train', sa.Integer(), nullable=True),
    sa.Column('n_test', sa.Integer(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_prediction_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('predicted_growth_pct', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('actual_growth_pct', sa.Float(), nullable=True),
    sa.Column('actual_measured_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'set_number', name='uq_ml_prediction_snapshot')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_cost_cents', sa.BigInteger(), nullable=False),
    sa.Column('total_market_value_cents', sa.BigInteger(), nullable=False),
    sa.Column('unrealized_pl_cents', sa.BigInteger(), nullable=False),
    sa.Column('realized_pl_cents', sa.BigInteger(), nullable=False),
    sa.Column('holdings_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('txn_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='MYR', nullable=False),
    sa.Column('condition', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('txn_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='MYR', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('shop_name', sa.String(length=200), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('dimensional_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('scrape_task_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_task_attempts_task_id'), 'scrape_task_attempts', ['task_id'], unique=False)
    op.create_table('scrape_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='3', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('depends_on', sa.String(length=50), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('set_minifigures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_item_id', sa.String(length=50), nullable=False),
    sa.Column('minifig_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('set_item_id', 'minifig_id', name='uq_set_minifigures')
    )
    op.create_table('shopee_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price_display', sa.String(length=50), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('sold_count', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('shop_name', sa.String(length=200), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_sold_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_url')
    )
    op.create_table('shopee_saturation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_number', sa.String(length=20), nullable=False),
    sa.Column('listings_count', sa.Integer(), nullable=False),
    sa.Column('unique_sellers', sa.Integer(), nullable=False),
    sa.Column('min_price_cents', sa.Integer(), nullable=True),
    sa.Column('max_price_cents', sa.Integer(), nullable=True),
    sa.Column('avg_price_cents', sa.Integer(), nullable=True),
    sa.Column('median_price_cents', sa.Integer(), nullable=True),
    sa.Column('price_spread_pct', sa.Float(), nullable=True),
    sa.Column('saturation_score', sa.Float(), nullable=False),
    sa.Column('saturation_level', sa.String(length=20), nullable=False),
    sa.Column('search_query', sa.String(length=200), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopee_scrape_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('items_found', sa.Integer(), server_default='0', nullable=False),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toysrus_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('price_myr', sa.String(length=20), nullable=False),
    sa.Column('available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toysrus_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price_myr', sa.String(length=20), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('age_range', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toysrus_products')
    op.drop_table('toysrus_price_history')
    op.drop_table('shopee_scrape_history')
    op.drop_table('shopee_saturation')
    op.drop_table('shopee_products')
    op.drop_table('set_minifigures')
    op.drop_table('scrape_tasks')
    op.drop_index(op.f('ix_scrape_task_attempts_task_id'), table_name='scrape_task_attempts')
    op.drop_table('scrape_task_attempts')
    op.drop_table('product_analysis')
    op.drop_table('price_records')
    op.drop_table('portfolio_transactions')
    op.drop_table('portfolio_snapshots')
    op.drop_table('ml_prediction_snapshots')
    op.drop_table('ml_model_runs')
    op.drop_table('ml_feature_store')
    op.drop_table('minifigures')
    op.drop_index(op.f('ix_minifig_price_history_minifig_id'), table_name='minifig_price_history')
    op.drop_table('minifig_price_history')
    op.drop_table('mightyutan_products')
    op.drop_table('mightyutan_price_history')
    op.drop_table('lego_items')
    op.drop_table('keepa_snapshots')
    op.drop_table('image_assets')
    op.drop_table('google_trends_theme_snapshots')
    op.drop_table('google_trends_snapshots')
    op.drop_index(op.f('ix_bricklink_price_history_item_id'), table_name='bricklink_price_history')
    op.drop_table('bricklink_price_history')
    op.drop_table('bricklink_monthly_sales')
    op.drop_table('bricklink_items')
    op.drop_table('brickeconomy_snapshots')
    # ### end Alembic commands ###
